packages:
  - "packages/desktop"
  - "packages/agent-server"
  - "packages/tui"
allowBuilds:
  '@google/genai': true
  protobufjs: true
minimumReleaseAgeExclude:
  - '@ai-sdk/gateway@4.0.3'
  - '@ai-sdk/mcp@2.0.2'
  - '@ai-sdk/react@4.0.4'
  - ai@7.0.3
